version: 0.1
   
phases:
  install:
    commands:
      - gem install bundle jekyll
      - bundle install
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://balloons-inc