version: 0.1
   
phases:
  install:
    commands:
      - gem install bundle jekyll
      - bundle install
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://balloonsinc.co.uk --exclude "*" --include "*.html" --cache-control max-age=3600
      - aws s3 sync _site/ s3://balloonsinc.co.uk --exclude "*.html" --exclude ".htaccess" --cache-control max-age=86400