version: 0.1
   
phases:
  install:
    commands:
      - gem install bundle jekyll
      - bundle install
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 ********"
<<<<<<< HEAD
      - aws s3 sync _site/ s3://balloonsinc.co.uk --exclude "*" --include "*.html" --cache-control max-age=3600
      - aws s3 sync _site/ s3://balloonsinc.co.uk --exclude "*.html" --exclude ".htaccess" --cache-control max-age=86400
=======
      - aws s3 sync _site/ s3://balloons-inc --exclude "*" --include "*.html" --cache-control max-age=3600
      - aws s3 sync _site/ s3://balloons-inc --exclude "*.html" --exclude ".htaccess" --cache-control max-age=86400
>>>>>>> 8f9b9bd67ba51814b67990bc265bbdd81aa56cb2
