name: Deploy to Firebase Hosting on Contentful publish event
'on':
  workflow_dispatch:
  repository_dispatch:
    types: 
      - ctf-publish
jobs:
  build:
    name: Build code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: rewrite-nuxt
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install NPM dependencies
        run: npm ci
      - name: Nuxt generate
        run: CTF_SPACE_ID=${{ secrets.CTF_SPACE_ID }} CTF_CDA_ACCESS_TOKEN=${{ secrets.CTF_CDA_ACCESS_TOKEN }} FLK_API_KEY=${{ secrets.FLK_API_KEY }} npm run generate
  deploy:
    name: Push to hosting
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BALLOONS_INC }}'
          channelId: live
          projectId: balloons-inc
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
