name: Deploy to Firebase Hosting on Contentful publish event
'on':
  repository_dispatch:
    types: 
      - ctf-publish
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && CTF_SPACE_ID=${{ secrets.CTF_SPACE_ID }} CTF_CDA_ACCESS_TOKEN=${{ secrets.CTF_CDA_ACCESS_TOKEN }} FLK_API_KEY=${{ secrets.FLK_API_KEY }} npm run generate
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BALLOONS_INC }}'
          channelId: live
          projectId: balloons-inc
          ref: rewrite-nuxt
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
